### ISSUE TITLE
Begin the workshop with lightning talks in key interest areas

### ISSUE THREAD

**Issue by csuwildcat** [w3c/blockchain#3]
On the call there were a few areas of interest expressed by the group that are reflected on the workshop site:

Core technical components of blockchains and their overlap with the Web, such as:
- Blockchain APIs, such as JavaScript or REST APIs
- Blockchain primitives such as transaction initiation, key signing, and wallet management
- Ledger interchange formats and protocols
- Smart contracts and conditional execution contexts

Application areas, such as:
- Identity systems, including privacy, security, and confidentiality factors
- Rights expression and licensing
- Decentralized processing, computing, and storage infrastructure
- Voting systems

I propose that we pick a group the attendees (with an interest specific focus areas above) to give 5 minute, introductory lightning talks that introduce their focus area and talk about how it can be a useful for developers and the Web at large. I would tell them to stay away from proscribing solutions, and instead focus on being informational.

**Comment by dazzaji** [comment]
I'm not sure of best format (eg quick talks, picking attendees or other) but do agree the program should be anchored the key topics identified on the event page (ie the core tech bullets and application domain area bullets). The event format should be aimed at revealing good candidates for W3C standards work, not solely great discussion of the topics.   
- If the format uses lightning talks as the main way to convey information to all attendees, then perhaps the first or last talk should focus on when something is suitable for standardization. 
- If there are breakouts that are facilitated, the facilitator could also maintain this relevant context and/or report outs from small groups could spotlight readiness for standardization along with what they are reporting (eg: "our group discussed x, y and z and identified X as a good potential candidate for standardization because ...").

To keep it top of mind, here are some pointers Doug shared on the list with general criteria for when something is suitable for standardization: 

1) Is there a clear problem statement that this would solve, for a significant number of people?

2) Is there a good starting point, such as a clear solution, or a set of competing solutions?

3) Do we have the right stakeholders ready to commit to the work, including implementers who would deploy the feature, and individuals willing to write, review, and test the specification?

For standardization at W3C specifically, we focus on the Web, in three main areas:
- client-side (browser-based) features, like markup languages, JavaScript APIs, or user-facing features; this is our main focus
- data and formats, such as interchange formats, vocabularies/ontologies, and languages to manipulate data; note that this area is usually treated with some skepticism by browser makers
- communication protocols; we do this much more rarely, typically only when there's a corresponding client-side API, and usually in partnership with IETF

**Comment by dazzaji** [comment]
Files added to repo where nice Git-powered content iteration can happen:
- [application-areas.md](https://github.com/w3c/blockchain/blob/master/application-areas.md)
- [technical-components.md](https://github.com/w3c/blockchain/blob/master/technical-components.md)
- [standards.md](https://github.com/w3c/blockchain/blob/master/standards.md)

**Comment by dazzaji** [comment]
Given that most of the topic areas listed in this issue are framed pretty well as potential areas that would need or greatly benefit from standard interoperability, I've added them into a [running list](https://github.com/w3c/blockchain/pull/10/files) of potential workshop candidate areas for focused attention.

**Comment by dazzaji** [comment]
I hear thunder... and soon we shall see lightning (talks)!  

This issue has been successfully resolved.
